/*
 * This source file was generated by the Gradle 'init' task
 */
package poo.colecoes;

import java.util.ArrayList;

public class App {
    
    public static void main(String[] args) {
        ArrayList<String> lista = new ArrayList<>();
        ArrayList<Pessoa> contatos = new ArrayList<>();

        lista.add("900");
        lista.add("300");
        lista.add("360");

        contatos.add(new Pessoa("Albert Einstein", "albert@mc2.com"));
        contatos.add(new Pessoa("Isaac Newton", "newton@apple.com"));
        contatos.add(new Pessoa("Galileo Galilei", "galileo@isthecenter.com"));

        for (Pessoa pessoa : contatos) {
            System.out.println(pessoa);            
        }

        // Expressão lambda
        contatos.forEach(pessoa -> {System.out.println(pessoa);});

        // Method reference
        contatos.forEach(System.out::println);
        System.out.println();

        lista.forEach(System.out::print);
        System.out.println();
        
        lista.remove("900");
        lista.forEach(System.out::print);
        System.out.println();
        
        lista.removeIf(elemento -> elemento.equals("300"));
        lista.forEach(System.out::println);
        System.out.println();

        contatos.removeIf(pessoa -> pessoa.getNome().equals("Albert Einstein"));

        Pessoa p = contatos.stream()
                    .filter(elemento -> elemento
                    .getNome()
                    .equals("Isaac Newton"))
                    .findFirst()
                    .orElse(null);

        Pessoa p2 = contatos.stream()
                    .filter(elemento -> elemento
                    .getNome()
                    .equals("José Newton"))
                    .findFirst()
                    .orElse(null);
        
        System.out.println(p);
        
        
        if (p2 != null) {
            String n = p2.getNome();
            System.out.println(n);
        } else {
            System.out.println("nome não consta");;
        }

            

    }
}
