/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        
        Scanner scanner = new Scanner(System.in);

        int linha = 1;

        while (scanner.hasNextLine()) {
            String line = scanner.nextLine().toUpperCase();
            System.out.println(linha + ": " + line);
            linha++;            
        }
        
    }
}
