/*
 * This source file was generated by the Gradle 'init' task
 */
package aula19.uml;

public class App {
    public static void main(String[] args) {
        
        Aviao a380 = new Aviao(24, 853, 575000, 3200000, 4, false);

        System.out.println(a380);

    }
}
