/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        String[] linhas = new String[3];
        int i = 0;
        
        while (scanner.hasNextLine()) {
            linhas[i] = scanner.nextLine();
            i++;
            if (i >= 3) {
                break;
            }        
        }

        System.out.println();

        System.out.println(linhas[0].charAt(0) + " \u2551 " + linhas[0].charAt(1) + " \u2551 " + linhas[0].charAt(2));
        System.out.println("\u2550 \u2550 \u2550 \u2550 \u2550");
        System.out.println(linhas[1].charAt(0) + " \u2551 " + linhas[1].charAt(1) + " \u2551 " + linhas[1].charAt(2));
        System.out.println("\u2550 \u2550 \u2550 \u2550 \u2550");
        System.out.println(linhas[2].charAt(0) + " \u2551 " + linhas[2].charAt(1) + " \u2551 " + linhas[2].charAt(2));

        System.out.println();

            
    }
        

}

