/*
 * This source file was generated by the Gradle 'init' task
 */
package aula20.associacao;

import java.util.ArrayList;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Agenda agenda = new Agenda();

        Scanner scanner = new Scanner(System.in);
        boolean menuAberto = true;

        while (menuAberto) {
            menu();

            System.out.println();
            System.out.println("Digite a opção escolhida: ");

            int opcao = scanner.nextInt();
            scanner.nextLine();

            switch (opcao) {
                case 1: {
                    System.out.println("Digite o nome:");
                    String nome = scanner.nextLine();
                    System.out.println("Digite o sobrenome:");
                    String sobrenome = scanner.nextLine();
                    System.out.println("Digite a data de nascimento (dd/MM/aaaa):");
                    String dataNascimento = scanner.nextLine();
                    System.out.println();

                    Contato contato = new Contato(nome, sobrenome, dataNascimento);

                    if (agenda.addContato(contato)) {
                        System.out.println("Contato adicionado com sucesso!");
                    } else {
                        System.out.println("Contato já existe na agenda!");
                    }

                    break;
                }
                case 2: {
                    System.out.println("Digite o nome do contato:");
                    String nome = scanner.nextLine();
                    System.out.println("Digite o sobrenome do contato:");
                    String sobrenome = scanner.nextLine();

                    ArrayList<Contato> encontrados = agenda.findContatos(nome, sobrenome);

                    System.out.println();
                    if (encontrados.isEmpty()) {
                        System.out.println("\nNenhum contato encontrado.\n");
                    } else {
                        for (Contato c : encontrados) {
                            System.out.println("--------------------------------------------------\n");
                            System.out.println(c.toString());
                            System.out.println("--------------------------------------------------\n");
                        }
                    }
                    break;
                }

                case 3: {
                    System.out.println("Digite o índice do contato a ser removido:");
                    int indice = scanner.nextInt() - 1;
                    scanner.nextLine();

                    if (agenda.removeContato(indice)) {
                        System.out.println("Contato removido com sucesso!");
                    } else {
                        System.out.println("Índice inválido. Contato não encontrado.");
                    }
                    break;
                }

                case 4:
                    System.out.println("Digite o índice do contato adicionar o telefone:");
                    int indice = scanner.nextInt() - 1;
                    scanner.nextLine();
                    System.out.println("Digite o rótulo do telefone (Pessoal ou Profissional):");
                    String rotulo = scanner.nextLine();
                    System.out.println("Digite o telefone (somente números):");
                    String telefone = scanner.nextLine();

                    if (agenda.addTelefone(rotulo, telefone, indice)) {
                        System.out.println("Telefone adicionado com sucesso!");
                    } else {
                        System.out.println("Erro ao adicionar telefone. Verifique os dados informados.");
                    }

                    break;
                case 5:
                    System.out.println("Digite o índice do contato adicionar o email:");
                    indice = scanner.nextInt() - 1;
                    scanner.nextLine();
                    System.out.println("Digite o rótulo do email (Pessoal ou Profissional):");
                    rotulo = scanner.nextLine();
                    System.out.println("Digite o email:");
                    String email = scanner.nextLine();

                    if (agenda.addEmail(rotulo, email, indice)) {
                        System.out.println("Email adicionado com sucesso!");
                    } else {
                        System.out.println("Erro ao adicionar email. Verifique os dados informados.");
                    }

                    break;
                case 6:
                    System.out.println("Digite o índice do contato remover o telefone:");
                    indice = scanner.nextInt() - 1;
                    scanner.nextLine();
                    System.out.println("Digite o rótulo do telefone a ser removido (Pessoal ou Profissional):");
                    rotulo = scanner.nextLine();

                    if (agenda.removeTelefone(rotulo, indice)) {
                        System.out.println("Telefone removido com sucesso!");
                    } else {
                        System.out.println("Erro ao remover telefone. Verifique os dados informados.");
                    }

                    break;
                case 7:
                    System.out.println("Digite o índice do contato remover o email:");
                    indice = scanner.nextInt() - 1;
                    scanner.nextLine();
                    System.out.println("Digite o rótulo do email a ser removido (Pessoal ou Profissional):");
                    rotulo = scanner.nextLine();

                    if (agenda.removeEmail(rotulo, indice)) {
                        System.out.println("Email removido com sucesso!");
                    } else {
                        System.out.println("Erro ao remover email. Verifique os dados informados.");
                    }

                    break;
                case 8:
                    System.out.println("Digite o índice do contato atualizar o telefone:");
                    indice = scanner.nextInt() - 1;
                    scanner.nextLine();
                    System.out.println("Digite o rótulo do telefone a ser atualizado (Pessoal ou Profissional):");
                    rotulo = scanner.nextLine();
                    System.out.println("Digite o novo telefone (somente números):");
                    telefone = scanner.nextLine();

                    if (agenda.updateTelefone(rotulo, telefone, indice)) {
                        System.out.println("Telefone atualizado com sucesso!");
                    } else {
                        System.out.println("Erro ao atualizar telefone. Verifique os dados informados.");
                    }

                    break;
                case 9:
                    System.out.println("Digite o índice do contato atualizar o email:");
                    indice = scanner.nextInt() - 1;
                    scanner.nextLine();
                    System.out.println("Digite o rótulo do email a ser atualizado (Pessoal ou Profissional):");
                    rotulo = scanner.nextLine();
                    System.out.println("Digite o novo email:");
                    email = scanner.nextLine();

                    if (agenda.updateEmail(rotulo, email, indice)) {
                        System.out.println("Email atualizado com sucesso!");
                    } else {
                        System.out.println("Erro ao atualizar email. Verifique os dados informados.");
                    }

                    break;
                case 10:
                    System.out.println(agenda.toString());
                    break;
                case 0:
                    menuAberto = false;
                    System.out.println("Até logo.");
                    break;
                default:
                    System.out.println("Opção inválida. Por favor digite novamente.");
                    break;
            }

            System.out.println();
            System.out.println("Pressione Enter para continuar...");
            scanner.nextLine();

        }

        scanner.close();

    }

    public static void menu() {
        System.out.println();
        System.out.println("1 - Adicionar Contato");
        System.out.println("2 - Buscar Contato");
        System.out.println("3 - Remover Contato");
        System.out.println("4 - Adicionar Telefone");
        System.out.println("5 - Adicionar Email");
        System.out.println("6 - Remover Telefone");
        System.out.println("7 - Remover Email");
        System.out.println("8 - Atualizar Telefone");
        System.out.println("9 - Atualizar Email");
        System.out.println("10 - Listar Contatos");
        System.out.println("0 - Sair");
        System.out.println();
    }
}
